name: CI
on: pull_request
jobs:
  lint-pr:
    name: Lint pull request title
    runs-on: ubuntu-latest
    steps:
      - name: Lint pull request title
        uses: jef/conventional-commits-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Format
        run: |
          UNFORMATTED_FILES=$(npm run format:check)
          if [ -n "$UNFORMATTED_FILES" ]; then
            echo "Unformatted files found:"
            echo "$UNFORMATTED_FILES"
            exit 1
          fi
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
